# Generated by Django 3.2.12 on 2023-08-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100, null=True)),
                ('number', models.IntegerField(null=True)),
                ('x', models.CharField(max_length=20, null=True)),
                ('y', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
