# Generated by Django 3.2.12 on 2023-08-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='number',
            new_name='altura',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='street',
            new_name='calle',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='x',
            new_name='latitud',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='y',
            new_name='longitud',
        ),
        migrations.AddField(
            model_name='address',
            name='codigo_postal',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='nomenclatura',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='partida',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
