# Generated by Django 3.2.12 on 2023-08-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230804_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='altura',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='codigo_postal',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
