# Generated by Django 3.2.12 on 2023-08-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_address_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Errorrs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('detail', models.TextField()),
            ],
        ),
    ]
