# Generated by Django 3.2.12 on 2023-08-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20230810_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='error',
            old_name='altura_conf',
            new_name='altura',
        ),
        migrations.RenameField(
            model_name='error',
            old_name='calle_conf',
            new_name='calle',
        ),
        migrations.RenameField(
            model_name='error',
            old_name='codigo_postal_conf',
            new_name='codigo_postal',
        ),
        migrations.AddField(
            model_name='error',
            name='nomenclatura',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='error',
            name='partida',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
