# Generated by Django 3.2.20 on 2023-09-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20230818_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='HojaDeRuta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.TextField()),
                ('codigo_postal', models.CharField(max_length=100, null=True)),
                ('calle', models.CharField(max_length=100, null=True)),
                ('altura', models.CharField(max_length=100, null=True)),
                ('partida', models.CharField(max_length=100, null=True)),
                ('nomenclatura', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
