# Generated by Django 3.2.20 on 2023-09-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_hojaderuta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oficios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.TextField()),
                ('tipo', models.CharField(max_length=100, null=True)),
                ('calle', models.CharField(max_length=100, null=True)),
                ('altura', models.CharField(max_length=100, null=True)),
                ('estado', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
