# Generated by Django 3.2.20 on 2023-09-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20230906_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficios',
            name='detalle',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
