# Generated by Django 3.2.12 on 2023-09-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_oficios_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficios',
            name='latitud',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='oficios',
            name='longitud',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
