# Generated by Django 3.2.20 on 2023-09-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20230907_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficios',
            name='latitud',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='oficios',
            name='longitud',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
