# Generated by Django 3.2.20 on 2023-09-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20230907_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficios',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
