# Generated by Django 3.2.12 on 2023-09-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_oficios_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hojaderuta',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='hojaderuta',
            name='calle',
        ),
        migrations.RemoveField(
            model_name='hojaderuta',
            name='codigo_postal',
        ),
        migrations.RemoveField(
            model_name='hojaderuta',
            name='nomenclatura',
        ),
        migrations.RemoveField(
            model_name='hojaderuta',
            name='partida',
        ),
        migrations.AddField(
            model_name='hojaderuta',
            name='idusuarioGenerador',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hojaderuta',
            name='listadoAInspeccionar',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='hojaderuta',
            name='listadoInspectores',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='hojaderuta',
            name='observaciones',
            field=models.TextField(null=True),
        ),
    ]
