# Generated by Django 3.2.12 on 2023-09-21 12:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20230921_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hojaderuta',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
